config/routes.rb
Rails.application.routes.draw do
  resources :walkers
  resources :walks
  resources :dogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
    has_many :walks
    has_many :walkers, through: :walks

    validates :name, :breed, :age, :sex, presence: true 
    
    def sorted_walks
        sorted = self.walks.sort_by{|walk| walk.datetime}
        sorted.reverse 
    end
end

app/models/walk.rb
class Walk < ApplicationRecord
    belongs_to :dog
    belongs_to :walker
end

app/models/walker.rb
class Walker < ApplicationRecord
    has_many :walks
    has_many :dogs, through: :walks

    validates :first_name, :last_name, :email, :image_url, presence: true
    validates :first_name, uniqueness: {scope: :last_name}

    def fullname
        "#{self.first_name} #{self.last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    def index
        @dogs = Dog.all
    end

    def show
        @dog = Dog.find(params[:id])
    end

    def new 
        @dog = Dog.new
    end

    def create
        @dog = Dog.create(dog_params)

        if @dog.valid?
            redirect_to dog_path(@dog)
        else
            flash[:dog_errors] = @dog.errors.full_messages
            redirect_to new_dog_path
        end

    end


    private

    def dog_params
        params.require(:dog).permit(:name, :breed, :age, :sex)
    end

end

app/controllers/walkers_controller.rb
class WalkersController < ApplicationController
    def index
        @walkers = Walker.all 
    end

    def show
        @walker = Walker.find(params[:id])
    end

    def new
        @walker = Walker.new 
    end

    def create
        @walker = Walker.create(walker_params)

        if @walker.valid?
            redirect_to walker_path(@walker)
        else
            flash[:walker_errors] = @walker.errors.full_messages
            redirect_to new_walker_path
        end
    end

    def edit
        @walker = Walker.find(params[:id]) 
    end

    def update
        @walker = Walker.find(params[:id])
        
        if @walker.update(walker_params)
            redirect_to walker_path(@walker)
        else
            flash[:errors] = @walker.errors.full_messages
            redirect_to edit_walker_path
        end
    end


    private

    def walker_params
        params.require(:walker).permit(:first_name, :last_name, :email, :image_url)
    end

end

app/controllers/walks_controller.rb
class WalksController < ApplicationController
    def new
        @walk = Walk.new 
    end

    def create
        @walk = Walk.create(walk_params)

        redirect_to dog_path(@walk.dog_id)
    end

    def destroy
        @walk = Walk.find(params[:id])
        @walk.destroy
        redirect_to dog_path(@walk.dog)
    end

    private

    def walk_params
        params.require(:walk).permit(:walker_id, :dog_id, :datetime)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/walkers_helper.rb
module WalkersHelper
end

app/helpers/walks_helper.rb
module WalksHelper
end

app/views/dogs/index.html.erb
<h1>Dogs</h1>

<% @dogs.each do |dog| %>
    <p>
        <%= link_to dog.name, dog_path(dog) %>
    </p>
<% end %>

app/views/dogs/new.html.erb
<%= form_for @dog do |f| %>
    <% if flash[:dog_errors] %>
        <% flash[:dog_errors].each do |error| %>
            <%= error %>
        <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :breed %>
    <%= f.text_field :breed %>
    <%= f.label :age %>
    <%= f.number_field :age %>
    <%= f.label :sex %>
    <%= f.label :m %>
    <%= f.radio_button :sex, "M"  %>
    <%= f.label :f %>
    <%= f.radio_button :sex, "F" %>

    <%= f.submit %>
<% end %>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>

<h3>Breed: <%= @dog.breed %></h2>

<h3>Age: <%= @dog.age %></h2>

<h3>Sex: <%= @dog.sex %></h2>

<h2>Walks:</h2>

<% @dog.sorted_walks.each do |walk| %>
    <p>
        <%= walk.datetime %> :

        <%= walk.walker.first_name %>
        <%= walk.walker.last_name %>

        
        <%= button_to "Delete Walk", walk_path(walk), method: :delete %>
    </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogWalking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/walkers/_form.html.erb
<%= form_for @walker do |f| %>
    <% if flash[:walker_errors] %>
        <% flash[:walker_errors].each do |error| %>
            <%= error %>
        <% end %>
    <% end %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
    
    <%= f.submit %>
<% end %>

app/views/walkers/edit.html.erb
<%= render "form" %>

app/views/walkers/index.html.erb
<h1>Walkers</h1>

<% @walkers.each do |walker| %>
    <% fullname = walker.first_name + " " + walker.last_name%>
    <p>
        <%= link_to fullname, walker_path(walker) %>
    </p>
<% end %>

app/views/walkers/new.html.erb
<%= render "form" %>

app/views/walkers/show.html.erb
<h1><%= @walker.first_name %> 
    <%= @walker.last_name %>
</h1>

<h2><%= @walker.email %></h2>

<img src="<%= @walker.image_url %>" alt="Walker Picture">

<p><%= link_to 'Edit Walker', edit_walker_path %></p>

app/views/walks/new.html.erb
<%= form_for @walk do |f| %>
  
  <%= f.label :walker %>
  <%= f.collection_select :walker_id, Walker.all, :id, :fullname, prompt: true %>

  <%= f.label :dog %>
  <%= f.collection_select :dog_id, Dog.all, :id, :name, prompt: true %>

  <%= f.label :datetime %>
  <%= f.datetime_field :datetime %>

    <%= f.submit %>
<% end %>